In [1]:
import pandas as pd
import numpy as np
import random as rd

In [5]:
zip_in_zone = [75001, 75002, 75003, 75004, 75005, 75006, 75007]
nb_of_zips = len(zip_in_zone)
days_planned = 30

#DISTANCE MATRIX
dist_matrix = np.zeros([nb_of_zips, nb_of_zips])
dist_matrix[np.triu_indices(nb_of_zips, 1)] = [rd.randint(1,10) for i in range(int((nb_of_zips-1)*nb_of_zips*.5))]
dist_matrix += dist_matrix.T

available_timeslots = pd.DataFrame(np.array([[0 for zip in zip_in_zone] for i in range(days_planned)]), columns=zip_in_zone)

print(dist_matrix)
print(available_timeslots)

[[ 0.  2.  3.  6.  7.  4.  3.]
 [ 2.  0. 10.  8.  5.  7.  5.]
 [ 3. 10.  0.  6.  4.  8.  3.]
 [ 6.  8.  6.  0.  2.  2.  7.]
 [ 7.  5.  4.  2.  0.  3.  1.]
 [ 4.  7.  8.  2.  3.  0. 10.]
 [ 3.  5.  3.  7.  1. 10.  0.]]
    75001  75002  75003  75004  75005  75006  75007
0       0      0      0      0      0      0      0
1       0      0      0      0      0      0      0
2       0      0      0      0      0      0      0
3       0      0      0      0      0      0      0
4       0      0      0      0      0      0      0
5       0      0      0      0      0      0      0
6       0      0      0      0      0      0      0
7       0      0      0      0      0      0      0
8       0      0      0      0      0      0      0
9       0      0      0      0      0      0      0
10      0      0      0      0      0      0      0
11      0      0      0      0      0      0      0
12      0      0      0      0      0      0      0
13      0      0      0      0      0      0      0
14

In [3]:
#UPDATE TIMESLOT AVAILABILITY

#execute SQL query to get previous and next visit adress
#...
available_techs = pd.read_csv('../available_techs.csv')

#add data of base point for each tech



print(available_techs)



    employee_id  previous_visit_postal_code  next_visit_postal_code
0            97                         NaN                     NaN
1            75                         NaN                     NaN
2           146                     75012.0                     NaN
3            96                         NaN                 31400.0
4           212                         NaN                     NaN
5           123                         NaN                     NaN
6           193                         NaN                     NaN
7           161                         NaN                     NaN
8           233                         NaN                     NaN
9           186                         NaN                     NaN
10          145                     75015.0                 75013.0
11          231                         NaN                     NaN
12          226                         NaN                     NaN
13          129                         NaN     

In [ ]:
#CHECK DISTANCE BETWEEN CLIENT ADRESS AND EACH TECH IN

